name: 'Dependent blocks linter'
description: 'Runs the blockwatch linter to analyze dependent blocks of code'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # ensures that git diff is available for previous commits

    - name: Install blockwatch
      run: |
        cargo install blockwatch
      shell: bash

    - name: Run blockwatch
      run: |
        git diff --patch origin/${{ github.base_ref }}...${{ github.sha }} | blockwatch
      shell: bash
