name: 'Dependent blocks linter'
description: 'Runs the blockwatch linter to analyze dependent blocks of code'

inputs:
  extensions:
    description: 'Extensions to pass to blockwatch in the format "key1=value1,key2=value2"'
    required: false
    default: ''
  enable:
    description: 'Validators to enable (comma separated)'
    required: false
    default: ''
  disable:
    description: 'Validators to disable (comma separated)'
    required: false
    default: ''
  ignore:
    description: 'Glob patterns for files to ignore (comma separated)'
    required: false
    default: ''
  globs:
    description: 'Glob patterns for files to check (comma separated)'
    required: false
    default: ''
  diff_pathspec:
    description: "Additional git diff pathspecs or options to filter the diff (e.g., ':(exclude).github/' or multiple separated by spaces)"
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # ensures that git diff is available for previous commits

    - name: Install blockwatch
      run: |
        cargo install blockwatch
      shell: bash

    - name: Run blockwatch on diff
      id: diff
      run: |
        # Process inputs
        # Use an array to store arguments to handle spaces within arguments correctly
        BLOCKWATCH_ARGS=()

        # Helper function to add arguments
        add_args() {
          local flag="$1"
          local input="$2"
          if [[ -n "$input" ]]; then
            # Replace newlines with commas to handle multiline inputs
            local clean_input="${input//$'\n'/,}"
            IFS=',' read -ra ITEMS <<< "$clean_input"
            for item in "${ITEMS[@]}"; do
              # Trim leading/trailing whitespace
              item="$(echo "$item" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
              if [[ -n "$item" ]]; then
                if [[ -n "$flag" ]]; then
                  BLOCKWATCH_ARGS+=("$flag" "$item")
                else
                  BLOCKWATCH_ARGS+=("$item")
                fi
              fi
            done
          fi
        }

        add_args "-E" "${{ inputs.extensions }}"
        add_args "-e" "${{ inputs.enable }}"
        add_args "-d" "${{ inputs.disable }}"
        add_args "--ignore" "${{ inputs.ignore }}"
        add_args "" "${{ inputs.globs }}"

        # Prepare optional diff pathspec/args from input
        DIFF_PATHSPEC="${{ inputs.diff_pathspec }}"

        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          # For Pull Requests: Compare the target branch base with the PR head commit
          # Use -- to separate revisions from pathspecs if provided
          if [[ -n "$DIFF_PATHSPEC" ]]; then
            # shellcheck disable=SC2086
            git diff --patch origin/${{ github.base_ref }}...${{ github.sha }} -- $DIFF_PATHSPEC | blockwatch "${BLOCKWATCH_ARGS[@]}"
          else
            git diff --patch origin/${{ github.base_ref }}...${{ github.sha }} | blockwatch "${BLOCKWATCH_ARGS[@]}"
          fi

        elif [[ "${{ github.event_name }}" == "push" ]]; then
          # For Pushes: Compare the commit before the push with the current/after commit
          BEFORE_SHA="${{ github.event.before }}"
          CURRENT_SHA="${{ github.sha }}" # same as github.event.after for push events

          # Handle the initial push to a new branch where BEFORE_SHA is 0000...
          if [[ "$BEFORE_SHA" == "0000000000000000000000000000000000000000" ]]; then
            # Use git diff --root so that pathspecs can be applied as well
            if [[ -n "$DIFF_PATHSPEC" ]]; then
              # shellcheck disable=SC2086
              git diff --patch --root $CURRENT_SHA -- $DIFF_PATHSPEC | blockwatch "${BLOCKWATCH_ARGS[@]}"
            else
              git diff --patch --root $CURRENT_SHA | blockwatch "${BLOCKWATCH_ARGS[@]}"
            fi
          else
            if [[ -n "$DIFF_PATHSPEC" ]]; then
              # shellcheck disable=SC2086
              git diff --patch $BEFORE_SHA...$CURRENT_SHA -- $DIFF_PATHSPEC | blockwatch "${BLOCKWATCH_ARGS[@]}"
            else
              git diff --patch $BEFORE_SHA...$CURRENT_SHA | blockwatch "${BLOCKWATCH_ARGS[@]}"
            fi
          fi

        else
          echo "Warning: Unsupported event type '${{ github.event_name }}'. Skipping diff."
        fi
      shell: bash
